-- 코드를 입력하세요
SELECT DISTINCT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
FROM PRODUCT A, OFFLINE_SALE B
where A.PRODUCT_ID=B.PRODUCT_ID
group by A.PRODUCT_CODE 
order by SALES DESC, A.PRODUCT_CODE ASC