-- 코드를 작성해주세요
select ROUTE, CONCAT(ROUND(sum(D_BETWEEN_DIST),1),'km')AS TOTAL_DISTANCE, CONCAT(ROUND(avg(D_BETWEEN_DIST),2),'km')AS AVERAGE_DISTANCE
from SUBWAY_DISTANCE
group by ROUTE
order by SUM(D_BETWEEN_DIST) DESC;