SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A, ITEM_TREE B
WHERE A.ITEM_ID=B.ITEM_ID 
# 부모가 rare
AND B.PARENT_ITEM_ID IN
(select item_id
from item_info
where RARITY='rare')
ORDER BY A.ITEM_ID DESC